#include <stdint.h>
#define RCC_CTRL_PLL3RDY 29
#define RCC_CTRL_PLL3ON 28
#define RCC_CTRL_PLL2RDY 27
#define RCC_CTRL_PLL2ON 26
#define RCC_CTRL_PLLRDY 25
#define RCC_CTRL_PLLON 24
#define RCC_CTRL_CSSON 19
#define RCC_CTRL_HSEBYP 18
#define RCC_CTRL_HSERDY 17
#define RCC_CTRL_HSEON 16
#define RCC_CTRL_HSICAL 8 // размер регистра 8 бит
#define RCC_CTRL_HSITRIM4 7
#define RCC_CTRL_HSITRIM3 6
#define RCC_CTRL_HSITRIM2 5
#define RCC_CTRL_HSITRIM1 4
#define RCC_CTRL_HSITRIM0 3
#define RCC_CTRL_HSIRDY 1
#define RCC_CTRL_HSION 0

#define RCC_CFGR0_ADCDUTY 31
#define RCC_CFGR0_ADC_DUTY_SEL 30
#define RCC_CFGR0_ETHPRE 28
#define RCC_CFGR0_MCO3 27
#define RCC_CFGR0_MCO2 26
#define RCC_CFGR0_MCO1 25
#define RCC_CFGR0_MCO0 24
#define RCC_CFGR0_USBPRE1 23
#define RCC_CFGR0_USBPRE0 22
#define RCC_CFGR0_PLLMUL3 21
#define RCC_CFGR0_PLLMUL2 20
#define RCC_CFGR0_PLLMUL1 19
#define RCC_CFGR0_PLLMUL0 18
#define RCC_CFGR0_PLLXTPRE 17
#define RCC_CFGR0_PLLSRC 16
#define RCC_CFGR0_ADCPRE1 15
#define RCC_CFGR0_ADCPRE0 14
#define RCC_CFGR0_PPRE22 13
#define RCC_CFGR0_PPRE21 12
#define RCC_CFGR0_PPRE20 11
#define RCC_CFGR0_PPRE12 10
#define RCC_CFGR0_PPRE11 9
#define RCC_CFGR0_PPRE10 8
#define RCC_CFGR0_HPRE3 7
#define RCC_CFGR0_HPRE2 6
#define RCC_CFGR0_HPRE1 5
#define RCC_CFGR0_HPRE0 4
#define RCC_CFGR0_SWS1 3
#define RCC_CFGR0_SWS0 2
#define RCC_CFGR0_SW1 1
#define RCC_CFGR0_SW0 0

#define RCC_INTR_CSSC 23
#define RCC_INTR_PLL3RDYC 22
#define RCC_INTR_PLL2RDYC 21
#define RCC_INTR_PLLRDYC 20
#define RCC_INTR_HSERDYC 19
#define RCC_INTR_HSIRDYC 18
#define RCC_INTR_LSERDYC 17
#define RCC_INTR_LSIRDYC 16
#define RCC_INTR_PLL3RDYIE 14
#define RCC_INTR_PLL2RDYIE 13
#define RCC_INTR_PLLRDYIE 12
#define RCC_INTR_HSERDYIE 11
#define RCC_INTR_HSIRDYIE 10
#define RCC_INTR_LSERDYIE 9
#define RCC_INTR_LSIRDYIE 8
#define RCC_INTR_CSSF 7
#define RCC_INTR_PLL3RDYF 6
#define RCC_INTR_PLL2RDYF 5
#define RCC_INTR_PLLRDYF 4
#define RCC_INTR_HSERDYF 3
#define RCC_INTR_HSIRDYF 2
#define RCC_INTR_LSERDYF 1
#define RCC_INTR_LSIRDYF 0

#define RCC_APB2PRSTR_TIM10RST 20
#define RCC_APB2PRSTR_TIM9RST 19
#define RCC_APB2PRSTR_USART1RST 14
#define RCC_APB2PRSTR_TIM8RST 13
#define RCC_APB2PRSTR_SPI1RST 12
#define RCC_APB2PRSTR_TIM1RST 11
#define RCC_APB2PRSTR_ADC2RST 10
#define RCC_APB2PRSTR_ADC1RST 9
#define RCC_APB2PRSTR_IOPERST 8
#define RCC_APB2PRSTR_IOPDRST 5
#define RCC_APB2PRSTR_IOPCRST 4
#define RCC_APB2PRSTR_IOPBRST 3
#define RCC_APB2PRSTR_IOPARST 2
#define RCC_APB2PRSTR_AFIORST 0

#define RCC_APB1PRSTR_DACRST 29
#define RCC_APB1PRSTR_PWRRST 28
#define RCC_APB1PRSTR_BKPRST 27
#define RCC_APB1PRSTR_CAN2RST 26
#define RCC_APB1PRSTR_CAN1RST 25
#define RCC_APB1PRSTR_USBDRST 23
#define RCC_APB1PRSTR_I2C2RST 22
#define RCC_APB1PRSTR_I2C1RST 21
#define RCC_APB1PRSTR_USART5RST 20
#define RCC_APB1PRSTR_USART4RST 19
#define RCC_APB1PRSTR_USART3RST 18
#define RCC_APB1PRSTR_USART2RST 17
#define RCC_APB1PRSTR_SPI3RST 15
#define RCC_APB1PRSTR_SPI2RST 14
#define RCC_APB1PRSTR_WWDGRST 11
#define RCC_APB1PRSTR_USART8RST 8
#define RCC_APB1PRSTR_USART7RST 7
#define RCC_APB1PRSTR_USART6RST 6
#define RCC_APB1PRSTR_TIM7RST 5
#define RCC_APB1PRSTR_TIM6RST 4
#define RCC_APB1PRSTR_TIM5RST 3
#define RCC_APB1PRSTR_TIM4RST 2
#define RCC_APB1PRSTR_TIM3RST 1
#define RCC_APB1PRSTR_TIM2RST 0

#define RCC_AHBPCENR_BLES 17
#define RCC_AHBPCENR_BLEC 16
#define RCC_AHBPCENR_ETHMACRXEN 15
#define RCC_AHBPCENR_ETHMACTXEN 14
#define RCC_AHBPCENR_ETHMACEN 14
#define RCC_AHBPCENR_DVPEN 13
#define RCC_AHBPCENR_OTG_FSEN 12
#define RCC_AHBPCENR_USBHSEN 11
#define RCC_AHBPCENR_SDIOEN 10
#define RCC_AHBPCENR_RNGEN 9
#define RCC_AHBPCENR_FSMCEN 8
#define RCC_AHBPCENR_CRCEN 6
#define RCC_AHBPCENR_SRAMEN 2
#define RCC_AHBPCENR_DMA2EN 1
#define RCC_AHBPCENR_DMA1EN 0

#define RCC_APB2PCENR_TIM10EN 20
#define RCC_APB2PCENR_TIM9EN 19

typedef struct
{
    uint32_t CTLR;
    uint32_t CFGR0;
    uint32_t INTR;
    uint32_t APB2PRSTR;
    uint32_t APB1PRSTR;
    uint32_t AHBPCENR;
    uint32_t APB1PCENR;
    uint32_t BDCTRL;
    uint32_t RSTSCKR;
    uint32_t AHBRSTR;
    uint32_t CFGR2;
} RCC_typedef;
